### ISSUE TITLE
Suggestion: web app version?

### ISSUE THREAD

**Issue by breck7** [515hikaru/mdtable2csv#15]
I have 1 markdown table to convert so just looking for a textarea somewhere to paste it in and get the CSV. Just a suggestion!

I found this via a google search.

Cool stuff!

**Comment by 515hikaru** [comment]
Thank you for your suggestion! But I will not create web app because there are already such service, like https://tableconvert.com/ .

This tool has very limted uses, and I find it convenient for CLI user. But if you want to use browser, need more features and reconstruction UX design(if not, it will be unuseful). I think that it's beyond this tool.
